{% set name = "sphinx_parser" %}
{% set version = "0.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3f445ba316b408d1d76e99a669e8b776e03d3ad71b31c7039599c0694cf99fb6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - versioneer
  run:
    - python >={{ python_min }}
    - numpy >=1.26.4,<2.4.0
    - ase >=3.23.0,<3.26.0
    - h5py >=3.6.0,<3.15.0
    - semantikon =0.0.20
    - pint >=0.23,<=0.24.4

test:
  imports:
    - sphinx_parser
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/pyiron/sphinx_parser
  summary: 'Parser for the DFT program SPHInX'
  description: |
    sphinx_parser is the python input and output parser of the DFT code SPHInX
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://sphinx_parser.readthedocs.io/
  dev_url: https://github.com/pyiron/sphinx_parser

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
