schema_version: 1

context:
  name: sphinx_parser
  version: "0.1.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4dd74b0e6dad055530916f818ee44952d817a0c10767916259171962d6e11283

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - versioneer
  run:
    - python >=${{ python_min }}
    - numpy >=1.26.4,<2.4.0
    - ase >=3.23.0,<3.27.0
    - h5py >=3.6.0,<3.15.0
    - semantikon >=0.0.17,<0.0.23
    - pint >=0.23,<0.26

tests:
  - python:
      imports:
        - sphinx_parser
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Parser for the DFT program SPHInX
  description: |
    sphinx_parser is the python input and output parser of the DFT code SPHInX
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/sphinx_parser
  repository: https://github.com/pyiron/sphinx_parser
  documentation: https://sphinx_parser.readthedocs.io/

extra:
  recipe-maintainers:
    - jan-janssen
    - samwaseda
